#!/bin/sh
#looking4 20090128 could just use `w $1|head -n3|tail -n1`;

if [ $1 ]
then 
  if [ $1 == 'root' ]
  then
	echo "Probably best you don't know"
  else
	if [ -d "/home/$1" ]
	then
		YES=$(w|grep $1|awk '{print $5}'|grep -v days|grep -v m|sort|tail -n1)
		[ $YES ] && echo "Yes: $1 was active $YES (Mintues:Seconds) ago" || echo "Doesn't look like $1 is about"
	else
		echo "I don't see /home/$1, so I presume they don't exist"
	fi
  fi
else
	echo "Who are you looking for?"
fi
