#!/bin/bash
#pdf-extract ver 0.01 20130405 alexx.net

function help() {
    echo "using pdfimage or gs to extract jpg FROM or convert TO jpg respectively (or convert -all PDFs in CWD)"
    echo " $0 [-from|-to|-all] pdfiifiles.pdf [out_path/[prefix]] [-quick]"
    exit 1
}

function sanity() {
    #check that pdfimage and gs are installed
    if [ $1 == '-from' ]
    then
        if [ $( which pdfimage 2>&1 1>/dev/null) ]
        then
            echo "can't find pdfimage";
            help
        else
            return 1
        fi
    else
        if [ $( which gs 2>&1 1>/dev/null) ]
        then
            echo "can't find ghostscript (gs)"
            help
        else
            return 1
        fi
    fi
}


if [ ! $1 ]
then
    help
    exit 1
fi
PDF=$2
OUTPATH=./

if [ $3 ]
then
    OUTPATH=$3
    DIR4SANE=`dirname $OUTPATH`;
    if [ ! $DIR4SANE == '.' ]
    then
        #echo making sure $DIR4SANE exists
        mkdir -p $DIR4SANE
    else
        #echo making sure $OUTPATH ready to accept the images
        mkdir -p $OUTPATH
    fi
fi

sanity()

if [ ! -f $PDF ]
then
    echo "Which PDF file should I work on?"
    help
fi

if [ $1 == '-from' ]
then
    pdfimages -j $PDF $OUTPATH
elif [ $1 == '-to' ]
then
    if [ $4 ]
    then
        #gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -dLastPage=1 -sOutputFile=${OUTPATH}_%02d.jpg -dJPEGQ=100 -r72x72 -q $PDF -c quit #some fonts unreadable
        #gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -sOutputFile=${OUTPATH}_%02d.jpg -q $PDF -dJPEGQ=100 -c quit #some fonts unreadable
        #gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -dLastPage=1 -sOutputFile=${OUTPATH}_%02d.jpg -dJPEGQ=100 -r900x900 -q $PDF -c quit # max of 9000pxx9000px
        #gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -dLastPage=1 -sOutputFile=${OUTPATH}%03d.jpg -dJPEGQ=100 -q $PDF -c quit # did -r72x72
        gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -dLastPage=1 -sOutputFile=${OUTPATH}_%04d.jpg -dJPEGQ=70 -r250x250 -q $PDF -c quit
    else
        # count the number of pages in the pdf and set the %02d to match, i.e. 115 page PDF %03d 9 page %d 98 page %02d
        gs -dNOPAUSE -sDEVICE=jpeg -dFirstPage=1 -sOutputFile=${OUTPATH}_%03d.jpg -dJPEGQ=100 -r300x300 -q $PDF -c quit
    fi
elif [ $1 == '-all' ]
then
    for i in `ls *.pdf`; do pdf-extract -to $i ${i%.pdf}/${i%.pdf}_ ; done
else
    help
fi

