#!/bin/sh

chmod 755 websocket.demo.php                     # sanity
php -q websocket.demo.php &                      # The client will access this using ws://localhost:12345/
links http://localhost/phpwebsocket/client.html  # < you get to _this_ via your local http daemon
                                                 # you may have to change the path. Mine is:
# http://localhost/sites/github/webSockets/phpwebsocket/client.html
